services:
  web:
    build: .
    container_name: fastapi_web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app  # Canlı kod güncellemesi (Hot-reload) için
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dy.7446.Dy
      POSTGRES_DB: e_commerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # Veritabanı verilerinin silinmemesi için kalıcı disk alanı